name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer:v2
      - run: composer install --no-interaction --no-progress --prefer-dist
      - run: php -v && php -m
      - run: php artisan key:generate
      - run: php artisan migrate --env=testing --database=sqlite --force
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ':memory:'
      - run: php artisan test --testsuite=Feature --stop-on-failure

